# -*- coding: utf-8 -*-
"""bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjjYWZgSOwotZ4267aB3G299E0ozq-b9
"""

"""
Main bot logic.
Handles message flow, validation, LLM calls, and logging.
"""

import time
from telegram_api import get_updates, send_message
from validator import is_input_safe
from gemini_client import run_agent
from sheets_logger import log_to_sheet


def process_message(chat_id: int, user_text: str) -> None:
    """
    Processes a single user message:
    - validates input
    - calls LLM
    - logs conversation
    - sends reply
    """
    if not is_input_safe(user_text):
        warning = (
            "Your message contains unsupported characters. "
            "Please use English or Cyrillic letters, digits, dash (-), comma, or dot."
        )
        send_message(chat_id, warning)
        log_to_sheet(chat_id, user_text, warning)
        return

    try:
        bot_reply = run_agent(user_text)
    except Exception as e:
        print("run_agent ERROR:", e)
        bot_reply = "Sorry, internal error."

    log_to_sheet(chat_id, user_text, bot_reply)
    send_message(chat_id, bot_reply)


def start_bot() -> None:
    """
    Infinite loop that:
    - receives updates
    - extracts messages
    - processes each message
    """
    print("Bot is running...")
    offset = None

    while True:
        updates = get_updates(offset)

        if "result" in updates:
            for update in updates["result"]:
                offset = update["update_id"] + 1

                if "message" in update:
                    chat_id = update["message"]["chat"]["id"]
                    user_text = update["message"].get("text", "")
                    print("User:", user_text)
                    process_message(chat_id, user_text)

        time.sleep(1)