# -*- coding: utf-8 -*-
"""gemini_client.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FI3K_jOkGBQTHyGd8Q_Zgfw2DQ2EFKhp
"""

"""
Gemini API client wrapper.
Handles prompt construction and model invocation.
"""

import google.generativeai as genai
from config import GEMINI_API_KEY
from prompt_loader import build_full_prompt

FULL_PROMPT: str = build_full_prompt()

genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel(
    model_name="models/gemini-2.5-flash"
)


def run_agent(user_text: str) -> str:
    """
    Sends user input to Gemini model using the full system prompt.
    Returns model response as plain text.
    """
    prompt = FULL_PROMPT + "\n\nUser: " + user_text
    response = model.generate_content(prompt)
    return response.text