# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTtll_CvCVoo2ndzwPsw5UDM38b04vdq
"""

"""
Entry point for the VYSHYVANKA Telegram bot.
"""

from bot import start_bot

if __name__ == "__main__":
    start_bot()