# -*- coding: utf-8 -*-
"""prompt_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1x9hppS9OTxqPEii11YeCAaVf_pp7ZH
"""

"""
Loads system prompt and hallucination tests from files
and builds a combined prompt for the LLM.
"""

from config import SYSTEM_PROMPT_FILE, HALLUCINATION_TESTS_FILE


def load_file(path: str) -> str:
    """Reads a UTF‑8 text file and returns its content."""
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def build_full_prompt() -> str:
    """Combines system prompt and hallucination tests into one string."""
    system_prompt = load_file(SYSTEM_PROMPT_FILE)
    tests = load_file(HALLUCINATION_TESTS_FILE)
    return system_prompt + "\n\n=== HALLUCINATION TESTS ===\n" + tests