# -*- coding: utf-8 -*-
"""sheets_logger.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbEwxYifrYKMCIdJ8fAUy6QYkJXPKe6B
"""

"""
Google Sheets logging module.
Appends timestamped conversation logs to a spreadsheet.
"""

import gspread
from datetime import datetime
from oauth2client.service_account import ServiceAccountCredentials
from config import CREDENTIALS_FILE, SPREADSHEET_ID


def init_sheets():
    """Initializes Google Sheets client and returns the first sheet."""
    scope = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ]
    creds = ServiceAccountCredentials.from_json_keyfile_name(CREDENTIALS_FILE, scope)
    client = gspread.authorize(creds)
    return client.open_by_key(SPREADSHEET_ID).sheet1


sheet = init_sheets()


def log_to_sheet(user_id: str, user_text: str, bot_reply: str) -> None:
    """
    Appends a new log entry to Google Sheets.
    Columns:
    timestamp | user_id | user_message | bot_reply
    """
    try:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        sheet.append_row([timestamp, str(user_id), user_text, bot_reply])
    except Exception as e:
        print("SHEETS ERROR:", e)