# -*- coding: utf-8 -*-
"""telegram_api.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqfCON74qLkJZOWH_vqHWiGcgx9GIVZF
"""

"""
Telegram Bot API wrapper.
Handles sending and receiving messages.
"""

import requests
from config import TELEGRAM_TOKEN

BASE_URL = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}"


def get_updates(offset: int | None = None) -> dict:
    """Fetches updates from Telegram."""
    url = BASE_URL + "/getUpdates"
    params = {"timeout": 100, "offset": offset}
    return requests.get(url, params=params).json()


def send_message(chat_id: int | str, text: str) -> None:
    """Sends a text message to a Telegram chat."""
    url = BASE_URL + "/sendMessage"
    payload = {"chat_id": chat_id, "text": text}
    requests.post(url, json=payload)