# -*- coding: utf-8 -*-
"""validator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i95-4kR-_w2pNMLG_xF0QVz3A7-79PTB
"""

"""
Input validation module.
Ensures user messages contain only allowed characters.
"""

import re

ALLOWED_PATTERN = re.compile(r"^[A-Za-zА-Яа-яЁёІіЇїЄєҐґ0-9\s'\-,\.]+$")


def is_input_safe(text: str) -> bool:
    """
    Returns True if the text contains only allowed characters.
    Prevents SQL injection and unsafe symbols.
    """
    return bool(ALLOWED_PATTERN.match(text))